// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamodbTraining.Tests.V1.Controllers.DynamodbTrainingControllerTests.ConstructQuery~DynamodbTraining.V1.Boundary.Request.PersonQueryObject")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamodbTraining.Tests.V1.UseCase.GetByIdUseCaseTests.ConstructQuery~DynamodbTraining.V1.Boundary.Request.PersonQueryObject")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamodbTraining.Tests.V1.Gateways.DynamoDbGatewayTests.ConstructQuery(System.Guid)~DynamodbTraining.V1.Boundary.Request.PersonQueryObject")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamodbTraining.Tests.V1.E2ETests.GetByIdE2ETests.CreateJsonOptions~System.Text.Json.JsonSerializerOptions")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamodbTraining.Tests.V1.Controllers.DynamodbTrainingControllerTests.ConstructRequest~DynamodbTraining.V1.Boundary.Request.PersonRequestObject")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamodbTraining.Tests.V1.UseCase.UpdatePersonUseCaseTests.ConstructQuery(System.Guid)~DynamodbTraining.V1.Boundary.Request.PersonQueryObject")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamodbTraining.Tests.V1.UseCase.UpdatePersonUseCaseTests.ConstructRequest~DynamodbTraining.V1.Boundary.Request.PersonRequestObject")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:DynamodbTraining.Tests.V1.E2ETests.PostE2ETests.PostPersonReturnsCreated~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamodbTraining.Tests.V1.E2ETests.PostE2ETests.CreateJsonOptions~System.Text.Json.JsonSerializerOptions")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamodbTraining.Tests.V1.E2ETests.PatchE2ETests.GivenAUpdatePersonRequest~DynamodbTraining.V1.Boundary.Request.PersonRequestObject")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamodbTraining.Tests.V1.E2ETests.PatchE2ETests.GivenAUpdatePersonRequest(System.Guid)~DynamodbTraining.V1.Boundary.Request.PersonRequestObject")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamodbTraining.Tests.V1.E2ETests.PatchE2ETests.CreateJsonOptions~System.Text.Json.JsonSerializerOptions")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:DynamodbTraining.Tests.V1.E2ETests.PatchE2ETests.UpdatedPersonReturnsNoContact~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:DynamodbTraining.Tests.V1.E2ETests.PatchE2ETests.UpdatePersonReturnsBadRequest~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:DynamodbTraining.Tests.V1.E2ETests.PatchE2ETests.UpdatePersonReturnsNotFound~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:DynamodbTraining.Tests.V1.E2ETests.PostE2ETests.PostPersonReturnsBadRequestWithValidationErrors~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:DynamodbTraining.Tests.V1.E2ETests.PatchE2ETests.UpdatedPersonReturnsNoContent~System.Threading.Tasks.Task")]
